chore(cors): add cors middleware
MapColonies/work-standard pull request #12
Opened 2020-09-22 17:01 UTC by shimoncohen

2020-09-22 17:49 UTC, syncush requested changes

2020-09-22 17:49 UTC, syncush commented on projectTemplates/ts-server/src/serverBuilder.ts
> +    this.serverInstance.use(cors());
Move `body-parser` under `cors` middleware under `registerMiddleware()`, also rename `registerMiddleware()` to `registerMiddlewares()`

2020-09-22 17:49 UTC, syncush commented on projectTemplates/js-server/package.json
>  }
Add the relevant code in the js-server template.

2020-09-22 17:49 UTC, syncush commented
This is not a chore, it is a feature.

2020-09-23 10:16 UTC, syncush requested changes
1. You still havn't added the necessary code for the javascript server template
2. this is a feature not a chore, please edit the commit message.

2020-09-23 12:36 UTC, asafMasa approved these changes

2020-09-24 07:23 UTC, syncush approved these changes

2020-09-24 07:25 UTC, merged