Conf fix
MapColonies/work-standard pull request #26
Opened 2020-10-29 09:23 UTC by cl-shaharshavit-rnd

closes #24

2020-10-29 11:08 UTC, asafMasa approved these changes

2020-10-29 12:36 UTC, syncush requested changes

2020-10-29 12:36 UTC, syncush commented on projectTemplates/ts-server/dockerfile
> +RUN cp /confd/confd ./confd/confd
Should be a one line

`RUN mkdir ./confd && cp /confd/confd ./confd/confd`

2020-10-29 12:36 UTC, syncush commented on projectTemplates/ts-server/dockerfile
>  COPY ./package*.json ./
Let's also not run as a root user, some openshifts envs does not allow to run as root.

2020-11-04 08:24 UTC, syncush approved these changes

2020-11-04 14:12 UTC, merged